import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import './gsap/setup'
// Virtual module generated by vite.config.js — only bundles the exact icon SVG
// data used in the app. Eliminates all runtime calls to api.iconify.design.
import 'virtual:iconify-offline'
import App from './App.jsx'
import './i18n';

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
